"""remove played_year add started_at finished_at

Revision ID: 06a68421cf14
Revises: e242eaac097d
Create Date: 2026-06-23 22:15:17.815399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a68421cf14'
down_revision: Union[str, Sequence[str], None] = 'e242eaac097d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_games', 'played_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('played_year', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
