"""revision order_index to tierCategoryitem

Revision ID: 81d8abdfde99
Revises: 91b0c0c4cfbf
Create Date: 2026-06-24 09:17:40.999626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d8abdfde99'
down_revision: Union[str, Sequence[str], None] = '91b0c0c4cfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier_items', sa.Column('order_index', sa.Integer(), nullable=False))
    op.drop_column('tierlists', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tierlists', sa.Column('order_index', sa.INTEGER(), nullable=False))
    op.drop_column('tier_items', 'order_index')
    # ### end Alembic commands ###
