"""add started_at finished_at to user_game

Revision ID: e242eaac097d
Revises: 2b6195b4ca71
Create Date: 2026-06-23 22:07:12.877383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e242eaac097d'
down_revision: Union[str, Sequence[str], None] = '2b6195b4ca71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('started_at', sa.Date(), nullable=True))
    op.add_column('user_games', sa.Column('finished_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_games', 'finished_at')
    op.drop_column('user_games', 'started_at')
    # ### end Alembic commands ###
